.PHONY: clean All

All:
	@echo "----------Building project:[ GameEngine - Debug ]----------"
	@cd "GameEngine" && "$(MAKE)" -f  "GameEngine.mk" && "$(MAKE)" -f  "GameEngine.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ GameEngine - Debug ]----------"
	@cd "GameEngine" && "$(MAKE)" -f  "GameEngine.mk" clean
